# Generated by Django 2.2.5 on 2019-09-25 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20190925_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2019, 9, 25, 20, 36, 39, 167887, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
