# Generated by Django 2.2.5 on 2019-09-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20190925_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='add_date',
            new_name='added_date',
        ),
    ]
