# Generated by Django 2.2.5 on 2019-09-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20190925_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='true',
            field=models.BooleanField(default='false'),
        ),
    ]
