# Generated by Django 2.2.5 on 2019-09-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20190925_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='true',
            field=models.BooleanField(),
        ),
    ]
