# Generated by Django 2.2.5 on 2019-09-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20190925_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='true',
        ),
    ]
